name: Node Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ["ubuntu-latest"]
    permissions:
      actions: read
      checks: write
      contents: read
      packages: write
      pull-requests: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout source
        uses: actions/checkout@v4
