name: Node Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ["ubuntu-latest"]
    permissions:
      actions: read
      checks: write
      contents: read
      packages: write
      pull-requests: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      BUILD_CONFIGURATION: Release
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
      DOTNET_INSTALL_DIR: '~/.dotnet'
    steps:
      - name: Install .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkout source
        uses: actions/checkout@v4
